[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-args=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
]

[target.x86_64-unknown-none]
rustflags = [
    "-Clink-arg=-Tsrc/linker-x86_64.ld",
    "-Cforce-frame-pointers=yes",
    '-Clink-arg=-no-pie',
    '--cfg=board="qemu"',
]

[target.aarch64-unknown-none-softfloat]
rustflags = [
    "-Clink-args=-Tsrc/linker-aarch64.ld", "-Cforce-frame-pointers=yes"
]

[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-args=-Tsrc/linker-aarch64.ld", "-Cforce-frame-pointers=yes"
]